export const flooringCategoryData = [
  {
    categoryId: 1,
    categoryHeading: "Shop by Collections",
    categoryData: [
      { id: 1, text: "Chevron" },
      { id: 2, text: "Exelam Hdf Laminates" },
      { id: 3, text: "Herringbone Flooring" },
      { id: 4, text: "Luxury Vinyl Planks 1.5 Mm" },
      { id: 5, text: "Spc Floorings 4.0 Mm" },
      { id: 6, text: "Spc Floorings 5.0 Mm" },
    ],
  },
  {
    categoryId: 2,
    categoryHeading: "Shop by Styles",
    categoryData: [
      { id: 1, text: "3 D Geometric" },
      { id: 2, text: "Abstract" },
      { id: 3, text: "Animal" },
      { id: 4, text: "Botanicals" },
      { id: 5, text: "Brick" },
      { id: 6, text: "Classic" },
      { id: 7, text: "Damask" },
      { id: 8, text: "Floral" },
      { id: 9, text: "Indian Heritage" },
      { id: 10, text: "Kids" },
    ],
  },
  {
    categoryId: 3,
    categoryHeading: "Shop by Colours",
    categoryData: [
      { id: 1, text: "Light Brown", image: "/Dropitemsimg/lightbrown.png" },
      { id: 2, text: "Beige", image: "/Dropitemsimg/beige.png"  },
      { id: 3, text: "Black", image: "/Dropitemsimg/black.avif" },
      { id: 4, text: "Brown", image: "/Dropitemsimg/brown.png" },
      { id: 5, text: "Canary Wood", image: "/Dropitemsimg/canarywood.jpg" },
      { id: 6, text: "Dark Brown", image: "/Dropitemsimg/darkbrown.png" },
      { id: 7, text: "Grey", image: "/Dropitemsimg/gray.png" },
    ],
  },
  {
    categoryId: 4,
    categoryHeading: "Shop by Rooms",
    categoryData: [
      { id: 1, text: "Bathroom" },
      { id: 2, text: "Bedroom" },
      { id: 3, text: "Dining Room" },
      { id: 4, text: "Kitchen" },
      { id: 5, text: "Living Room" },
      { id: 6, text: "Playroom" },
      { id: 7, text: "Office" },
      { id: 8, text: "Gym" },
    ],
  },
];
