export const wallpaperCategoryData = [
    {
      categoryId: 1,
      categoryHeading: "SHOP BY COLLECTIONS",
      categoryData: [
        { id: 1, text: "Allure" },
        { id: 2, text: "Altis" },
        { id: 3, text: "Aurora" },
        { id: 4, text: "Aventus" },
        { id: 5, text: "Avenue 8" },
        { id: 6, text: "Best Of Living Walls" },
        { id: 7, text: "Blooming" },
        { id: 8, text: "Brazil" },
        { id: 9, text: "Celebration" },
        { id: 10, text: "Darae 5" },
      ],
    },
    {
      categoryId: 2,
      categoryHeading: "SHOP BY STYLES",
      categoryData: [
        { id: 1, text: "3 D Geometric" },
        { id: 2, text: "Abstract" },
        { id: 3, text: "Animal" },
        { id: 4, text: "Botanicals" },
        { id: 5, text: "Brick" },
        { id: 6, text: "Classic" },
        { id: 7, text: "Damask" },
        { id: 8, text: "Floral" },
        { id: 9, text: "Indian Heritage" },
        { id: 10, text: "Kids" },
      ],
    },
    {
      categoryId: 3,
      categoryHeading: "SHOP BY COLOUR",
      categoryData: [
        { id: 1, text: "Beige", image: "/Dropitemsimg/beige.png" },
        { id: 2, text: "Black", image: "/Dropitemsimg/black.avif" },
        { id: 3, text: "Blue", image: "/Dropitemsimg/blue.png" },
        { id: 4, text: "Brown", image: "/Dropitemsimg/brown.png" },
        { id: 5, text: "Cream", image: "/Dropitemsimg/cream.jpeg" },
        { id: 6, text: "Golden", image: "/Dropitemsimg/golden.avif" },
        { id: 7, text: "Green", image: "/Dropitemsimg/green.png" },
        { id: 8, text: "Grey", image: "/Dropitemsimg/gray.png" },
        { id: 9, text: "Multicoloured", image: "/Dropitemsimg/bnw.png" },
        { id: 10, text: "Orange", image: "/Dropitemsimg/orange.avif" },
      ],
    },
    {
      categoryId: 4,
      categoryHeading: "SHOP BY ROOMS",
      categoryData: [
        { id: 1, text: "Bathroom" },
        { id: 2, text: "Bedroom" },
        { id: 3, text: "Dining Room" },
        { id: 4, text: "Kitchen" },
        { id: 5, text: "Living Room" },
        { id: 6, text: "Playroom" },
        { id: 7, text: "Office" },
        { id: 8, text: "Gym" },
      ],
    },
  ];