import { Inter } from 'next/font/google'
import './globals.css'
// import Header from '@/components/Header'
// import Footer from '@/components/Footer/Footer'
import Link from 'next/link'
const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Ayatrio',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
      <Link rel="icon" href="/favicon-32x32.png" sizes="any" ></Link>

      {/* <Header/> */}
      {children}</body>
      {/* <Footer/> */}
    </html>
  )
}
